model:
    arch: upernet
    backbone: mobilevit
data:
    dataset: lpcvc 
    train_split: train  
    val_split: val
    img_rows: 512
    img_cols: 512
    path: data/
training:
    n_workers: 16
    train_iters: 20000
    batch_size: 16
    val_interval: 500
    print_interval: 25
    prune: True
    prune_percentage: 0.9
    step_size: 20000
    teacher: 
        name:
            arch: upernet
            backbone: swin_v2_t
        model: runs/Uper_swin_v2_t/model/upernet_lpcvc_best_model.pkl
    loss:
        name: OhemCELoss2D
        thresh: 0.7
        ignore_index: 250
    optimizer:
        name: adaoptimizer
        momentum: 0.9
        lr_multi: 1
        bn_wd_disable: False
        wd: 5.0e-4
        lr0: 1.0e-3
        max_iter: 20000
        power: 0.9
        warmup_steps: 1000
        warmup_start_lr: 1.0e-5
    train_augmentations:
        rotate: 5
        brightness: 0.5
        contrast: 0.5
        saturation: 0.5
        scale: [512,512]
        rscale: [0.5,2]
        hflip: 0.5
        rcrop: [384,384]
        norm: 255.0
        cnorm: [[.485, .456, .406],[.229, .224, .225]]
    resume: ./runs/Uper_mobilevit/model_kd/upernet_lpcvc_best_model.pkl
    visdom: False

validating:
    densecrf: False
    resume: ./runs/FA_Res18/86059/fanet_lpcvc_best_model.pkl
    n_workers: 1
    batch_size: 1
    outpath: 
    val_augmentations:
        scale: [512,512]
        norm: 255.0
        cnorm: [[.485, .456, .406],[.229, .224, .225]]
