model:
    arch: upernet
    backbone: swin_v2_t
data:
    dataset: lpcvc 
    train_split: train  
    val_split: val
    img_rows: 512
    img_cols: 512
    path: data/
validating:
    densecrf: False
    resume: ./runs/Uper_swin_v2_t/prune_kd_0/prune_kd_0_0.9/upernet_lpcvc_best_model.pkl
    n_workers: 1
    batch_size: 1
    outpath: 
    val_augmentations:
        scale: [512,512]
        norm: 255.0
        cnorm: [[.485, .456, .406],[.229, .224, .225]]